# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-26 13:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0003_auto_20160326_1354'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='location.City'),
        ),
    ]
