# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-27 04:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_worker_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='role',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('worker', 'Worker')], max_length=120, null=True),
        ),
    ]
